version: '3.9'

networks:
  becoming:
    driver: bridge

services:
  becominghostapp:
    image: becominghostapp:latest
    container_name: becominghostapp
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Production"
      - "ConnectionStrings:PostgreSqlConnectionString=Host=host.docker.internal;Database=becoming;Username=postgres;Password=postgres;Port=5436"
    ports:
      - "7002:80"
    depends_on: 
      - postgresql
    networks:
      - becoming

  postgresql:
    image: postgres:15rc2-alpine
    container_name: becoming-postgresql
    restart: always
    # build:
    #   context: ./database-providers/postgresql
    #   dockerfile: DockerFile
    ports:
      - 5436:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: becoming
    networks:
      - becoming

